# site settings
title: Johnny
subtitle: by HTML5
email: littlejohnnyzq@icloud.com
description: 小囧尼是个不牛逼但热爱生活的设计狮<br /> 开心过每一天,用心做每件事.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 余杭 . 闲林山水
city: 杭州
state: 浙江
zip_code: 55555
country: 中国
phone: (+86)18521092332

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
