# site settings
title: Johnny
subtitle: walk
email: ltjnzq@163.com
github: littlejohnnyzq
description: 一个不牛逼但热爱生活的设计狮.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 浙江 . 杭州 . 天目山西路 . 闲林山水
city:
state:
zip_code:
country:
phone: (+86)18521092332

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
dribbble_url: https://dribbble.com
github_url: https://github.com/littlejohnnyzq
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
